/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://uhvey4ovqbaitnw5ymg6f2r7fq.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_cognito_identity_pool_id": "us-east-1:45fc0d23-5984-48d1-a665-6b3c0fb9c217",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_twUVGqhl6",
    "aws_user_pools_web_client_id": "7s0glosh7e7pku15rh34bcahi6",
    "oauth": {
        "domain": "adoptusd461506d-d461506d-staging.auth.us-east-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "http://localhost:3000/,https://www.adoptus.ca/",
        "redirectSignOut": "http://localhost:3000/,https://www.adoptus.ca/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [
        "FACEBOOK",
        "GOOGLE"
    ],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_mobile_analytics_app_id": "813a0681f06046e0b3e8d7b6ddb73ba5",
    "aws_mobile_analytics_app_region": "us-east-1",
    "Analytics": {
        "AWSPinpoint": {
            "appId": "813a0681f06046e0b3e8d7b6ddb73ba5",
            "region": "us-east-1"
        }
    }
};


export default awsmobile;
